//-
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory 
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
/////////////////////////////////////////////////////////////////////////////////
// This is an automatically generated header definitions file
/////////////////////////////////////////////////////////////////////////////////

//######################################################
//# Definitions for MICROBLAZE_AXI_IIC
//######################################################
#define SUME_MICROBLAZE_AXI_IIC_BASEADDR 0x40800000
#define SUME_MICROBLAZE_AXI_IIC_HIGHADDR 0x4080FFFF
#define SUME_MICROBLAZE_AXI_IIC_SIZEADDR 0x10000


//######################################################
//# Definitions for MICROBLAZE_UARTLITE
//######################################################
#define SUME_MICROBLAZE_UARTLITE_BASEADDR 0x40600000
#define SUME_MICROBLAZE_UARTLITE_HIGHADDR 0x4060FFFF
#define SUME_MICROBLAZE_UARTLITE_SIZEADDR 0x10000


//######################################################
//# Definitions for MICROBLAZE_DLMB_BRAM
//######################################################
#define SUME_MICROBLAZE_DLMB_BRAM_BASEADDR 0x00000000
#define SUME_MICROBLAZE_DLMB_BRAM_HIGHADDR 0x0000FFFF
#define SUME_MICROBLAZE_DLMB_BRAM_SIZEADDR 0x10000


//######################################################
//# Definitions for MICROBLAZE_ILMB_BRAM
//######################################################
#define SUME_MICROBLAZE_ILMB_BRAM_BASEADDR 0x00000000
#define SUME_MICROBLAZE_ILMB_BRAM_HIGHADDR 0x0000FFFF
#define SUME_MICROBLAZE_ILMB_BRAM_SIZEADDR 0x10000


//######################################################
//# Definitions for MICROBLAZE_AXI_INTC
//######################################################
#define SUME_MICROBLAZE_AXI_INTC_BASEADDR 0x41200000
#define SUME_MICROBLAZE_AXI_INTC_HIGHADDR 0x4120FFFF
#define SUME_MICROBLAZE_AXI_INTC_SIZEADDR 0x10000


//######################################################
//# Definitions for DELAY0
//######################################################
#define SUME_DELAY0_BASEADDR 0x44010000
#define SUME_DELAY0_HIGHADDR 0x44010FFF
#define SUME_DELAY0_SIZEADDR 0x1000

#define SUME_DELAY_0_ID_OFFSET 0x0
#define SUME_DELAY_0_ID_DEFAULT 0x0000DE00
#define SUME_DELAY_0_ID_WIDTH 32
#define SUME_DELAY_0_VERSION_OFFSET 0x4
#define SUME_DELAY_0_VERSION_DEFAULT 0x1
#define SUME_DELAY_0_VERSION_WIDTH 32
#define SUME_DELAY_0_RESET_OFFSET 0x8
#define SUME_DELAY_0_RESET_DEFAULT 0x0
#define SUME_DELAY_0_RESET_WIDTH 16
#define SUME_DELAY_0_FLIP_OFFSET 0xC
#define SUME_DELAY_0_FLIP_DEFAULT 0x0
#define SUME_DELAY_0_FLIP_WIDTH 32
#define SUME_DELAY_0_DEBUG_OFFSET 0x10
#define SUME_DELAY_0_DEBUG_DEFAULT 0x0
#define SUME_DELAY_0_DEBUG_WIDTH 32
#define SUME_DELAY_0_PKTIN_OFFSET 0x14
#define SUME_DELAY_0_PKTIN_DEFAULT 0x0
#define SUME_DELAY_0_PKTIN_WIDTH 32
#define SUME_DELAY_0_PKTOUT_OFFSET 0x18
#define SUME_DELAY_0_PKTOUT_DEFAULT 0x0
#define SUME_DELAY_0_PKTOUT_WIDTH 32
#define SUME_DELAY_0_DELAYVAL_OFFSET 0x1C
#define SUME_DELAY_0_DELAYVAL_DEFAULT 0x0
#define SUME_DELAY_0_DELAYVAL_WIDTH 32
#define SUME_DELAY_0_JITTERVAL_OFFSET 0x20
#define SUME_DELAY_0_JITTERVAL_DEFAULT 0x0
#define SUME_DELAY_0_JITTERVAL_WIDTH 32
#define SUME_DELAY_0_JITTERTYPE_OFFSET 0x24
#define SUME_DELAY_0_JITTERTYPE_DEFAULT 0x0
#define SUME_DELAY_0_JITTERTYPE_WIDTH 32
#define SUME_DELAY_0_INDIRECTADDRESS_OFFSET 0x50
#define SUME_DELAY_0_INDIRECTADDRESS_DEFAULT 0x0
#define SUME_DELAY_0_INDIRECTADDRESS_WIDTH 32
#define SUME_DELAY_0_INDIRECTWRDATA_OFFSET 0x54
#define SUME_DELAY_0_INDIRECTWRDATA_DEFAULT 0x0
#define SUME_DELAY_0_INDIRECTWRDATA_WIDTH 32
#define SUME_DELAY_0_INDIRECTREPLY_OFFSET 0x58
#define SUME_DELAY_0_INDIRECTREPLY_DEFAULT 0x0
#define SUME_DELAY_0_INDIRECTREPLY_WIDTH 32
#define SUME_DELAY_0_INDIRECTCOMMAND_OFFSET 0x5C
#define SUME_DELAY_0_INDIRECTCOMMAND_DEFAULT 0x0
#define SUME_DELAY_0_INDIRECTCOMMAND_WIDTH 32
#define SUME_DELAY_0_INDIRECTCONFIG_OFFSET 0x60
#define SUME_DELAY_0_INDIRECTCONFIG_DEFAULT 0x0
#define SUME_DELAY_0_INDIRECTCONFIG_WIDTH 32
#define SUME_DELAY_0__MEM_DISTMEM_WIDTH 32
#define SUME_DELAY_0__MEM_DISTMEM_DEPTH 65536
#define SUME_DELAY_0__MEM_DISTMEM_ADDRESS 0x0
#define SUME_DELAY_0__MEM_USERDISTMEM_WIDTH 32
#define SUME_DELAY_0__MEM_USERDISTMEM_DEPTH 65536
#define SUME_DELAY_0__MEM_USERDISTMEM_ADDRESS 0x10000000

//######################################################
//# Definitions for DELAY1
//######################################################
#define SUME_DELAY1_BASEADDR 0x44020000
#define SUME_DELAY1_HIGHADDR 0x44020FFF
#define SUME_DELAY1_SIZEADDR 0x1000

#define SUME_DELAY_1_ID_OFFSET 0x0
#define SUME_DELAY_1_ID_DEFAULT 0x0000DE00
#define SUME_DELAY_1_ID_WIDTH 32
#define SUME_DELAY_1_VERSION_OFFSET 0x4
#define SUME_DELAY_1_VERSION_DEFAULT 0x1
#define SUME_DELAY_1_VERSION_WIDTH 32
#define SUME_DELAY_1_RESET_OFFSET 0x8
#define SUME_DELAY_1_RESET_DEFAULT 0x0
#define SUME_DELAY_1_RESET_WIDTH 16
#define SUME_DELAY_1_FLIP_OFFSET 0xC
#define SUME_DELAY_1_FLIP_DEFAULT 0x0
#define SUME_DELAY_1_FLIP_WIDTH 32
#define SUME_DELAY_1_DEBUG_OFFSET 0x10
#define SUME_DELAY_1_DEBUG_DEFAULT 0x0
#define SUME_DELAY_1_DEBUG_WIDTH 32
#define SUME_DELAY_1_PKTIN_OFFSET 0x14
#define SUME_DELAY_1_PKTIN_DEFAULT 0x0
#define SUME_DELAY_1_PKTIN_WIDTH 32
#define SUME_DELAY_1_PKTOUT_OFFSET 0x18
#define SUME_DELAY_1_PKTOUT_DEFAULT 0x0
#define SUME_DELAY_1_PKTOUT_WIDTH 32
#define SUME_DELAY_1_DELAYVAL_OFFSET 0x1C
#define SUME_DELAY_1_DELAYVAL_DEFAULT 0x0
#define SUME_DELAY_1_DELAYVAL_WIDTH 32
#define SUME_DELAY_1_JITTERVAL_OFFSET 0x20
#define SUME_DELAY_1_JITTERVAL_DEFAULT 0x0
#define SUME_DELAY_1_JITTERVAL_WIDTH 32
#define SUME_DELAY_1_JITTERTYPE_OFFSET 0x24
#define SUME_DELAY_1_JITTERTYPE_DEFAULT 0x0
#define SUME_DELAY_1_JITTERTYPE_WIDTH 32
#define SUME_DELAY_1_INDIRECTADDRESS_OFFSET 0x50
#define SUME_DELAY_1_INDIRECTADDRESS_DEFAULT 0x0
#define SUME_DELAY_1_INDIRECTADDRESS_WIDTH 32
#define SUME_DELAY_1_INDIRECTWRDATA_OFFSET 0x54
#define SUME_DELAY_1_INDIRECTWRDATA_DEFAULT 0x0
#define SUME_DELAY_1_INDIRECTWRDATA_WIDTH 32
#define SUME_DELAY_1_INDIRECTREPLY_OFFSET 0x58
#define SUME_DELAY_1_INDIRECTREPLY_DEFAULT 0x0
#define SUME_DELAY_1_INDIRECTREPLY_WIDTH 32
#define SUME_DELAY_1_INDIRECTCOMMAND_OFFSET 0x5C
#define SUME_DELAY_1_INDIRECTCOMMAND_DEFAULT 0x0
#define SUME_DELAY_1_INDIRECTCOMMAND_WIDTH 32
#define SUME_DELAY_1_INDIRECTCONFIG_OFFSET 0x60
#define SUME_DELAY_1_INDIRECTCONFIG_DEFAULT 0x0
#define SUME_DELAY_1_INDIRECTCONFIG_WIDTH 32
#define SUME_DELAY_1__MEM_DISTMEM_WIDTH 32
#define SUME_DELAY_1__MEM_DISTMEM_DEPTH 65536
#define SUME_DELAY_1__MEM_DISTMEM_ADDRESS 0x0
#define SUME_DELAY_1__MEM_USERDISTMEM_WIDTH 32
#define SUME_DELAY_1__MEM_USERDISTMEM_DEPTH 65536
#define SUME_DELAY_1__MEM_USERDISTMEM_ADDRESS 0x10000000

//######################################################
//# Definitions for RATE_LIMITER0
//######################################################
#define SUME_RATE_LIMITER0_BASEADDR 0x44030000
#define SUME_RATE_LIMITER0_HIGHADDR 0x44030FFF
#define SUME_RATE_LIMITER0_SIZEADDR 0x1000

#define SUME_RATE_LIMITER_0_ID_OFFSET 0x0
#define SUME_RATE_LIMITER_0_ID_DEFAULT 0x0008DEAD
#define SUME_RATE_LIMITER_0_ID_WIDTH 32
#define SUME_RATE_LIMITER_0_VERSION_OFFSET 0x4
#define SUME_RATE_LIMITER_0_VERSION_DEFAULT 0x1
#define SUME_RATE_LIMITER_0_VERSION_WIDTH 32
#define SUME_RATE_LIMITER_0_RESET_OFFSET 0x8
#define SUME_RATE_LIMITER_0_RESET_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_RESET_WIDTH 16
#define SUME_RATE_LIMITER_0_FLIP_OFFSET 0xC
#define SUME_RATE_LIMITER_0_FLIP_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_FLIP_WIDTH 32
#define SUME_RATE_LIMITER_0_DEBUG_OFFSET 0x10
#define SUME_RATE_LIMITER_0_DEBUG_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_DEBUG_WIDTH 32
#define SUME_RATE_LIMITER_0_PKTIN_OFFSET 0x14
#define SUME_RATE_LIMITER_0_PKTIN_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_PKTIN_WIDTH 32
#define SUME_RATE_LIMITER_0_PKTOUT_OFFSET 0x18
#define SUME_RATE_LIMITER_0_PKTOUT_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_PKTOUT_WIDTH 32
#define SUME_RATE_LIMITER_0_RATEBASE_OFFSET 0x1C
#define SUME_RATE_LIMITER_0_RATEBASE_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_RATEBASE_WIDTH 32
#define SUME_RATE_LIMITER_0_RATEVALID_OFFSET 0x20
#define SUME_RATE_LIMITER_0_RATEVALID_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_RATEVALID_WIDTH 32
#define SUME_RATE_LIMITER_0_RATECONFIG_OFFSET 0x24
#define SUME_RATE_LIMITER_0_RATECONFIG_DEFAULT 0x0
#define SUME_RATE_LIMITER_0_RATECONFIG_WIDTH 32

//######################################################
//# Definitions for RATE_LIMITER1
//######################################################
#define SUME_RATE_LIMITER1_BASEADDR 0x44040000
#define SUME_RATE_LIMITER1_HIGHADDR 0x44040FFF
#define SUME_RATE_LIMITER1_SIZEADDR 0x1000

#define SUME_RATE_LIMITER_1_ID_OFFSET 0x0
#define SUME_RATE_LIMITER_1_ID_DEFAULT 0x0008DEAD
#define SUME_RATE_LIMITER_1_ID_WIDTH 32
#define SUME_RATE_LIMITER_1_VERSION_OFFSET 0x4
#define SUME_RATE_LIMITER_1_VERSION_DEFAULT 0x1
#define SUME_RATE_LIMITER_1_VERSION_WIDTH 32
#define SUME_RATE_LIMITER_1_RESET_OFFSET 0x8
#define SUME_RATE_LIMITER_1_RESET_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_RESET_WIDTH 16
#define SUME_RATE_LIMITER_1_FLIP_OFFSET 0xC
#define SUME_RATE_LIMITER_1_FLIP_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_FLIP_WIDTH 32
#define SUME_RATE_LIMITER_1_DEBUG_OFFSET 0x10
#define SUME_RATE_LIMITER_1_DEBUG_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_DEBUG_WIDTH 32
#define SUME_RATE_LIMITER_1_PKTIN_OFFSET 0x14
#define SUME_RATE_LIMITER_1_PKTIN_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_PKTIN_WIDTH 32
#define SUME_RATE_LIMITER_1_PKTOUT_OFFSET 0x18
#define SUME_RATE_LIMITER_1_PKTOUT_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_PKTOUT_WIDTH 32
#define SUME_RATE_LIMITER_1_RATEBASE_OFFSET 0x1C
#define SUME_RATE_LIMITER_1_RATEBASE_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_RATEBASE_WIDTH 32
#define SUME_RATE_LIMITER_1_RATEVALID_OFFSET 0x20
#define SUME_RATE_LIMITER_1_RATEVALID_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_RATEVALID_WIDTH 32
#define SUME_RATE_LIMITER_1_RATECONFIG_OFFSET 0x24
#define SUME_RATE_LIMITER_1_RATECONFIG_DEFAULT 0x0
#define SUME_RATE_LIMITER_1_RATECONFIG_WIDTH 32

//######################################################
//# Definitions for STATS0
//######################################################
#define SUME_STATS0_BASEADDR 0x44050000
#define SUME_STATS0_HIGHADDR 0x44050FFF
#define SUME_STATS0_SIZEADDR 0x1000

#define SUME_STATS_0_ID_OFFSET 0x0
#define SUME_STATS_0_ID_DEFAULT 0x000057A7
#define SUME_STATS_0_ID_WIDTH 32
#define SUME_STATS_0_VERSION_OFFSET 0x4
#define SUME_STATS_0_VERSION_DEFAULT 0x1
#define SUME_STATS_0_VERSION_WIDTH 32
#define SUME_STATS_0_RESET_OFFSET 0x8
#define SUME_STATS_0_RESET_DEFAULT 0x0
#define SUME_STATS_0_RESET_WIDTH 16
#define SUME_STATS_0_FLIP_OFFSET 0xC
#define SUME_STATS_0_FLIP_DEFAULT 0x0
#define SUME_STATS_0_FLIP_WIDTH 32
#define SUME_STATS_0_DEBUG_OFFSET 0x10
#define SUME_STATS_0_DEBUG_DEFAULT 0x0
#define SUME_STATS_0_DEBUG_WIDTH 32
#define SUME_STATS_0_PKTIN_OFFSET 0x14
#define SUME_STATS_0_PKTIN_DEFAULT 0x0
#define SUME_STATS_0_PKTIN_WIDTH 32
#define SUME_STATS_0_PKTOUT_OFFSET 0x18
#define SUME_STATS_0_PKTOUT_DEFAULT 0x0
#define SUME_STATS_0_PKTOUT_WIDTH 32
#define SUME_STATS_0_TESTTRIGGER_OFFSET 0x1C
#define SUME_STATS_0_TESTTRIGGER_DEFAULT 0x0
#define SUME_STATS_0_TESTTRIGGER_WIDTH 32
#define SUME_STATS_0_BWGRANULARITY_OFFSET 0x20
#define SUME_STATS_0_BWGRANULARITY_DEFAULT 0x30d40
#define SUME_STATS_0_BWGRANULARITY_WIDTH 32
#define SUME_STATS_0_BWDIVISOR_OFFSET 0x24
#define SUME_STATS_0_BWDIVISOR_DEFAULT 0x1
#define SUME_STATS_0_BWDIVISOR_WIDTH 32
#define SUME_STATS_0_BURSTGAP_OFFSET 0x28
#define SUME_STATS_0_BURSTGAP_DEFAULT 0x0
#define SUME_STATS_0_BURSTGAP_WIDTH 32
#define SUME_STATS_0_TESTEND_OFFSET 0x2C
#define SUME_STATS_0_TESTEND_DEFAULT 0x0
#define SUME_STATS_0_TESTEND_WIDTH 32
#define SUME_STATS_0_FIRSTTIME_OFFSET 0x30
#define SUME_STATS_0_FIRSTTIME_DEFAULT 0x0
#define SUME_STATS_0_FIRSTTIME_WIDTH 32
#define SUME_STATS_0_LASTTIME_OFFSET 0x34
#define SUME_STATS_0_LASTTIME_DEFAULT 0x0
#define SUME_STATS_0_LASTTIME_WIDTH 32
#define SUME_STATS_0_LASTBW_OFFSET 0x38
#define SUME_STATS_0_LASTBW_DEFAULT 0x0
#define SUME_STATS_0_LASTBW_WIDTH 32
#define SUME_STATS_0_INPUTSEL_OFFSET 0x3C
#define SUME_STATS_0_INPUTSEL_DEFAULT 0x0
#define SUME_STATS_0_INPUTSEL_WIDTH 32
#define SUME_STATS_0_ARPCOUNT_OFFSET 0x40
#define SUME_STATS_0_ARPCOUNT_DEFAULT 0x0
#define SUME_STATS_0_ARPCOUNT_WIDTH 32
#define SUME_STATS_0_IP4COUNT_OFFSET 0x44
#define SUME_STATS_0_IP4COUNT_DEFAULT 0x0
#define SUME_STATS_0_IP4COUNT_WIDTH 32
#define SUME_STATS_0_IP6COUNT_OFFSET 0x48
#define SUME_STATS_0_IP6COUNT_DEFAULT 0x0
#define SUME_STATS_0_IP6COUNT_WIDTH 32
#define SUME_STATS_0_TCPCOUNT_OFFSET 0x4C
#define SUME_STATS_0_TCPCOUNT_DEFAULT 0x0
#define SUME_STATS_0_TCPCOUNT_WIDTH 32
#define SUME_STATS_0_UDPCOUNT_OFFSET 0x50
#define SUME_STATS_0_UDPCOUNT_DEFAULT 0x0
#define SUME_STATS_0_UDPCOUNT_WIDTH 32
#define SUME_STATS_0_SYNCOUNT_OFFSET 0x54
#define SUME_STATS_0_SYNCOUNT_DEFAULT 0x0
#define SUME_STATS_0_SYNCOUNT_WIDTH 32
#define SUME_STATS_0_FINCOUNT_OFFSET 0x58
#define SUME_STATS_0_FINCOUNT_DEFAULT 0x0
#define SUME_STATS_0_FINCOUNT_WIDTH 32
#define SUME_STATS_0_FLOWIDCOUNT_OFFSET 0x5C
#define SUME_STATS_0_FLOWIDCOUNT_DEFAULT 0x0
#define SUME_STATS_0_FLOWIDCOUNT_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH1_OFFSET 0x60
#define SUME_STATS_0_PATTERNMATCH1_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH1_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH2_OFFSET 0x64
#define SUME_STATS_0_PATTERNMATCH2_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH2_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH3_OFFSET 0x68
#define SUME_STATS_0_PATTERNMATCH3_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH3_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH4_OFFSET 0x6C
#define SUME_STATS_0_PATTERNMATCH4_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH4_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH5_OFFSET 0x70
#define SUME_STATS_0_PATTERNMATCH5_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH5_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH6_OFFSET 0x74
#define SUME_STATS_0_PATTERNMATCH6_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH6_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH7_OFFSET 0x78
#define SUME_STATS_0_PATTERNMATCH7_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH7_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH8_OFFSET 0x7C
#define SUME_STATS_0_PATTERNMATCH8_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH8_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH9_OFFSET 0x80
#define SUME_STATS_0_PATTERNMATCH9_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH9_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH10_OFFSET 0x84
#define SUME_STATS_0_PATTERNMATCH10_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH10_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH11_OFFSET 0x88
#define SUME_STATS_0_PATTERNMATCH11_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH11_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH12_OFFSET 0x8C
#define SUME_STATS_0_PATTERNMATCH12_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH12_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH13_OFFSET 0x90
#define SUME_STATS_0_PATTERNMATCH13_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH13_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH14_OFFSET 0x94
#define SUME_STATS_0_PATTERNMATCH14_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH14_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH15_OFFSET 0x98
#define SUME_STATS_0_PATTERNMATCH15_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH15_WIDTH 32
#define SUME_STATS_0_PATTERNMATCH16_OFFSET 0x9C
#define SUME_STATS_0_PATTERNMATCH16_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMATCH16_WIDTH 32
#define SUME_STATS_0_PATTERNMASK1_OFFSET 0xA0
#define SUME_STATS_0_PATTERNMASK1_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK1_WIDTH 32
#define SUME_STATS_0_PATTERNMASK2_OFFSET 0xA4
#define SUME_STATS_0_PATTERNMASK2_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK2_WIDTH 32
#define SUME_STATS_0_PATTERNMASK3_OFFSET 0xA8
#define SUME_STATS_0_PATTERNMASK3_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK3_WIDTH 32
#define SUME_STATS_0_PATTERNMASK4_OFFSET 0xAC
#define SUME_STATS_0_PATTERNMASK4_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK4_WIDTH 32
#define SUME_STATS_0_PATTERNMASK5_OFFSET 0xB0
#define SUME_STATS_0_PATTERNMASK5_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK5_WIDTH 32
#define SUME_STATS_0_PATTERNMASK6_OFFSET 0xB4
#define SUME_STATS_0_PATTERNMASK6_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK6_WIDTH 32
#define SUME_STATS_0_PATTERNMASK7_OFFSET 0xB8
#define SUME_STATS_0_PATTERNMASK7_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK7_WIDTH 32
#define SUME_STATS_0_PATTERNMASK8_OFFSET 0xBC
#define SUME_STATS_0_PATTERNMASK8_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK8_WIDTH 32
#define SUME_STATS_0_PATTERNMASK9_OFFSET 0xC0
#define SUME_STATS_0_PATTERNMASK9_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK9_WIDTH 32
#define SUME_STATS_0_PATTERNMASK10_OFFSET 0xC4
#define SUME_STATS_0_PATTERNMASK10_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK10_WIDTH 32
#define SUME_STATS_0_PATTERNMASK11_OFFSET 0xC8
#define SUME_STATS_0_PATTERNMASK11_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK11_WIDTH 32
#define SUME_STATS_0_PATTERNMASK12_OFFSET 0xCC
#define SUME_STATS_0_PATTERNMASK12_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK12_WIDTH 32
#define SUME_STATS_0_PATTERNMASK13_OFFSET 0xD0
#define SUME_STATS_0_PATTERNMASK13_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK13_WIDTH 32
#define SUME_STATS_0_PATTERNMASK14_OFFSET 0xD4
#define SUME_STATS_0_PATTERNMASK14_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK14_WIDTH 32
#define SUME_STATS_0_PATTERNMASK15_OFFSET 0xD8
#define SUME_STATS_0_PATTERNMASK15_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK15_WIDTH 32
#define SUME_STATS_0_PATTERNMASK16_OFFSET 0xDC
#define SUME_STATS_0_PATTERNMASK16_DEFAULT 0x0
#define SUME_STATS_0_PATTERNMASK16_WIDTH 32
#define SUME_STATS_0_MATCHCOUNT_OFFSET 0xE0
#define SUME_STATS_0_MATCHCOUNT_DEFAULT 0x0
#define SUME_STATS_0_MATCHCOUNT_WIDTH 32
#define SUME_STATS_0_INDIRECTADDRESS_OFFSET 0x100
#define SUME_STATS_0_INDIRECTADDRESS_DEFAULT 0x0
#define SUME_STATS_0_INDIRECTADDRESS_WIDTH 32
#define SUME_STATS_0_INDIRECTWRDATA_OFFSET 0x104
#define SUME_STATS_0_INDIRECTWRDATA_DEFAULT 0x0
#define SUME_STATS_0_INDIRECTWRDATA_WIDTH 32
#define SUME_STATS_0_INDIRECTREPLY_OFFSET 0x108
#define SUME_STATS_0_INDIRECTREPLY_DEFAULT 0x0
#define SUME_STATS_0_INDIRECTREPLY_WIDTH 32
#define SUME_STATS_0_INDIRECTCOMMAND_OFFSET 0x10C
#define SUME_STATS_0_INDIRECTCOMMAND_DEFAULT 0x0
#define SUME_STATS_0_INDIRECTCOMMAND_WIDTH 32
#define SUME_STATS_0_INDIRECTCONFIG_OFFSET 0x110
#define SUME_STATS_0_INDIRECTCONFIG_DEFAULT 0x0
#define SUME_STATS_0_INDIRECTCONFIG_WIDTH 32
#define SUME_STATS_0__MEM_PKTSIZEMEM_WIDTH 32
#define SUME_STATS_0__MEM_PKTSIZEMEM_DEPTH 2048
#define SUME_STATS_0__MEM_PKTSIZEMEM_ADDRESS 0x0
#define SUME_STATS_0__MEM_IPGMEM_WIDTH 32
#define SUME_STATS_0__MEM_IPGMEM_DEPTH 4096
#define SUME_STATS_0__MEM_IPGMEM_ADDRESS 0x10000000
#define SUME_STATS_0__MEM_BURSTMEM_WIDTH 32
#define SUME_STATS_0__MEM_BURSTMEM_DEPTH 8192
#define SUME_STATS_0__MEM_BURSTMEM_ADDRESS 0x20000000
#define SUME_STATS_0__MEM_BWMEM_WIDTH 32
#define SUME_STATS_0__MEM_BWMEM_DEPTH 8192
#define SUME_STATS_0__MEM_BWMEM_ADDRESS 0x30000000
#define SUME_STATS_0__MEM_BWTSMEM_WIDTH 32
#define SUME_STATS_0__MEM_BWTSMEM_DEPTH 8192
#define SUME_STATS_0__MEM_BWTSMEM_ADDRESS 0x40000000
#define SUME_STATS_0__MEM_PPSMEM_WIDTH 32
#define SUME_STATS_0__MEM_PPSMEM_DEPTH 8192
#define SUME_STATS_0__MEM_PPSMEM_ADDRESS 0x50000000
#define SUME_STATS_0__MEM_FLOWIDMEM_WIDTH 32
#define SUME_STATS_0__MEM_FLOWIDMEM_DEPTH 2048
#define SUME_STATS_0__MEM_FLOWIDMEM_ADDRESS 0x60000000
#define SUME_STATS_0__MEM_WINDOWSIZEMEM_WIDTH 32
#define SUME_STATS_0__MEM_WINDOWSIZEMEM_DEPTH 2048
#define SUME_STATS_0__MEM_WINDOWSIZEMEM_ADDRESS 0x70000000

//######################################################
//# Definitions for STATS1
//######################################################
#define SUME_STATS1_BASEADDR 0x44060000
#define SUME_STATS1_HIGHADDR 0x44060FFF
#define SUME_STATS1_SIZEADDR 0x1000

#define SUME_STATS_1_ID_OFFSET 0x0
#define SUME_STATS_1_ID_DEFAULT 0x000057A7
#define SUME_STATS_1_ID_WIDTH 32
#define SUME_STATS_1_VERSION_OFFSET 0x4
#define SUME_STATS_1_VERSION_DEFAULT 0x1
#define SUME_STATS_1_VERSION_WIDTH 32
#define SUME_STATS_1_RESET_OFFSET 0x8
#define SUME_STATS_1_RESET_DEFAULT 0x0
#define SUME_STATS_1_RESET_WIDTH 16
#define SUME_STATS_1_FLIP_OFFSET 0xC
#define SUME_STATS_1_FLIP_DEFAULT 0x0
#define SUME_STATS_1_FLIP_WIDTH 32
#define SUME_STATS_1_DEBUG_OFFSET 0x10
#define SUME_STATS_1_DEBUG_DEFAULT 0x0
#define SUME_STATS_1_DEBUG_WIDTH 32
#define SUME_STATS_1_PKTIN_OFFSET 0x14
#define SUME_STATS_1_PKTIN_DEFAULT 0x0
#define SUME_STATS_1_PKTIN_WIDTH 32
#define SUME_STATS_1_PKTOUT_OFFSET 0x18
#define SUME_STATS_1_PKTOUT_DEFAULT 0x0
#define SUME_STATS_1_PKTOUT_WIDTH 32
#define SUME_STATS_1_TESTTRIGGER_OFFSET 0x1C
#define SUME_STATS_1_TESTTRIGGER_DEFAULT 0x0
#define SUME_STATS_1_TESTTRIGGER_WIDTH 32
#define SUME_STATS_1_BWGRANULARITY_OFFSET 0x20
#define SUME_STATS_1_BWGRANULARITY_DEFAULT 0x30d40
#define SUME_STATS_1_BWGRANULARITY_WIDTH 32
#define SUME_STATS_1_BWDIVISOR_OFFSET 0x24
#define SUME_STATS_1_BWDIVISOR_DEFAULT 0x1
#define SUME_STATS_1_BWDIVISOR_WIDTH 32
#define SUME_STATS_1_BURSTGAP_OFFSET 0x28
#define SUME_STATS_1_BURSTGAP_DEFAULT 0x0
#define SUME_STATS_1_BURSTGAP_WIDTH 32
#define SUME_STATS_1_TESTEND_OFFSET 0x2C
#define SUME_STATS_1_TESTEND_DEFAULT 0x0
#define SUME_STATS_1_TESTEND_WIDTH 32
#define SUME_STATS_1_FIRSTTIME_OFFSET 0x30
#define SUME_STATS_1_FIRSTTIME_DEFAULT 0x0
#define SUME_STATS_1_FIRSTTIME_WIDTH 32
#define SUME_STATS_1_LASTTIME_OFFSET 0x34
#define SUME_STATS_1_LASTTIME_DEFAULT 0x0
#define SUME_STATS_1_LASTTIME_WIDTH 32
#define SUME_STATS_1_LASTBW_OFFSET 0x38
#define SUME_STATS_1_LASTBW_DEFAULT 0x0
#define SUME_STATS_1_LASTBW_WIDTH 32
#define SUME_STATS_1_INPUTSEL_OFFSET 0x3C
#define SUME_STATS_1_INPUTSEL_DEFAULT 0x0
#define SUME_STATS_1_INPUTSEL_WIDTH 32
#define SUME_STATS_1_ARPCOUNT_OFFSET 0x40
#define SUME_STATS_1_ARPCOUNT_DEFAULT 0x0
#define SUME_STATS_1_ARPCOUNT_WIDTH 32
#define SUME_STATS_1_IP4COUNT_OFFSET 0x44
#define SUME_STATS_1_IP4COUNT_DEFAULT 0x0
#define SUME_STATS_1_IP4COUNT_WIDTH 32
#define SUME_STATS_1_IP6COUNT_OFFSET 0x48
#define SUME_STATS_1_IP6COUNT_DEFAULT 0x0
#define SUME_STATS_1_IP6COUNT_WIDTH 32
#define SUME_STATS_1_TCPCOUNT_OFFSET 0x4C
#define SUME_STATS_1_TCPCOUNT_DEFAULT 0x0
#define SUME_STATS_1_TCPCOUNT_WIDTH 32
#define SUME_STATS_1_UDPCOUNT_OFFSET 0x50
#define SUME_STATS_1_UDPCOUNT_DEFAULT 0x0
#define SUME_STATS_1_UDPCOUNT_WIDTH 32
#define SUME_STATS_1_SYNCOUNT_OFFSET 0x54
#define SUME_STATS_1_SYNCOUNT_DEFAULT 0x0
#define SUME_STATS_1_SYNCOUNT_WIDTH 32
#define SUME_STATS_1_FINCOUNT_OFFSET 0x58
#define SUME_STATS_1_FINCOUNT_DEFAULT 0x0
#define SUME_STATS_1_FINCOUNT_WIDTH 32
#define SUME_STATS_1_FLOWIDCOUNT_OFFSET 0x5C
#define SUME_STATS_1_FLOWIDCOUNT_DEFAULT 0x0
#define SUME_STATS_1_FLOWIDCOUNT_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH1_OFFSET 0x60
#define SUME_STATS_1_PATTERNMATCH1_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH1_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH2_OFFSET 0x64
#define SUME_STATS_1_PATTERNMATCH2_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH2_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH3_OFFSET 0x68
#define SUME_STATS_1_PATTERNMATCH3_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH3_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH4_OFFSET 0x6C
#define SUME_STATS_1_PATTERNMATCH4_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH4_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH5_OFFSET 0x70
#define SUME_STATS_1_PATTERNMATCH5_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH5_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH6_OFFSET 0x74
#define SUME_STATS_1_PATTERNMATCH6_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH6_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH7_OFFSET 0x78
#define SUME_STATS_1_PATTERNMATCH7_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH7_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH8_OFFSET 0x7C
#define SUME_STATS_1_PATTERNMATCH8_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH8_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH9_OFFSET 0x80
#define SUME_STATS_1_PATTERNMATCH9_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH9_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH10_OFFSET 0x84
#define SUME_STATS_1_PATTERNMATCH10_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH10_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH11_OFFSET 0x88
#define SUME_STATS_1_PATTERNMATCH11_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH11_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH12_OFFSET 0x8C
#define SUME_STATS_1_PATTERNMATCH12_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH12_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH13_OFFSET 0x90
#define SUME_STATS_1_PATTERNMATCH13_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH13_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH14_OFFSET 0x94
#define SUME_STATS_1_PATTERNMATCH14_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH14_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH15_OFFSET 0x98
#define SUME_STATS_1_PATTERNMATCH15_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH15_WIDTH 32
#define SUME_STATS_1_PATTERNMATCH16_OFFSET 0x9C
#define SUME_STATS_1_PATTERNMATCH16_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMATCH16_WIDTH 32
#define SUME_STATS_1_PATTERNMASK1_OFFSET 0xA0
#define SUME_STATS_1_PATTERNMASK1_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK1_WIDTH 32
#define SUME_STATS_1_PATTERNMASK2_OFFSET 0xA4
#define SUME_STATS_1_PATTERNMASK2_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK2_WIDTH 32
#define SUME_STATS_1_PATTERNMASK3_OFFSET 0xA8
#define SUME_STATS_1_PATTERNMASK3_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK3_WIDTH 32
#define SUME_STATS_1_PATTERNMASK4_OFFSET 0xAC
#define SUME_STATS_1_PATTERNMASK4_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK4_WIDTH 32
#define SUME_STATS_1_PATTERNMASK5_OFFSET 0xB0
#define SUME_STATS_1_PATTERNMASK5_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK5_WIDTH 32
#define SUME_STATS_1_PATTERNMASK6_OFFSET 0xB4
#define SUME_STATS_1_PATTERNMASK6_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK6_WIDTH 32
#define SUME_STATS_1_PATTERNMASK7_OFFSET 0xB8
#define SUME_STATS_1_PATTERNMASK7_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK7_WIDTH 32
#define SUME_STATS_1_PATTERNMASK8_OFFSET 0xBC
#define SUME_STATS_1_PATTERNMASK8_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK8_WIDTH 32
#define SUME_STATS_1_PATTERNMASK9_OFFSET 0xC0
#define SUME_STATS_1_PATTERNMASK9_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK9_WIDTH 32
#define SUME_STATS_1_PATTERNMASK10_OFFSET 0xC4
#define SUME_STATS_1_PATTERNMASK10_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK10_WIDTH 32
#define SUME_STATS_1_PATTERNMASK11_OFFSET 0xC8
#define SUME_STATS_1_PATTERNMASK11_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK11_WIDTH 32
#define SUME_STATS_1_PATTERNMASK12_OFFSET 0xCC
#define SUME_STATS_1_PATTERNMASK12_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK12_WIDTH 32
#define SUME_STATS_1_PATTERNMASK13_OFFSET 0xD0
#define SUME_STATS_1_PATTERNMASK13_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK13_WIDTH 32
#define SUME_STATS_1_PATTERNMASK14_OFFSET 0xD4
#define SUME_STATS_1_PATTERNMASK14_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK14_WIDTH 32
#define SUME_STATS_1_PATTERNMASK15_OFFSET 0xD8
#define SUME_STATS_1_PATTERNMASK15_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK15_WIDTH 32
#define SUME_STATS_1_PATTERNMASK16_OFFSET 0xDC
#define SUME_STATS_1_PATTERNMASK16_DEFAULT 0x0
#define SUME_STATS_1_PATTERNMASK16_WIDTH 32
#define SUME_STATS_1_MATCHCOUNT_OFFSET 0xE0
#define SUME_STATS_1_MATCHCOUNT_DEFAULT 0x0
#define SUME_STATS_1_MATCHCOUNT_WIDTH 32
#define SUME_STATS_1_INDIRECTADDRESS_OFFSET 0x100
#define SUME_STATS_1_INDIRECTADDRESS_DEFAULT 0x0
#define SUME_STATS_1_INDIRECTADDRESS_WIDTH 32
#define SUME_STATS_1_INDIRECTWRDATA_OFFSET 0x104
#define SUME_STATS_1_INDIRECTWRDATA_DEFAULT 0x0
#define SUME_STATS_1_INDIRECTWRDATA_WIDTH 32
#define SUME_STATS_1_INDIRECTREPLY_OFFSET 0x108
#define SUME_STATS_1_INDIRECTREPLY_DEFAULT 0x0
#define SUME_STATS_1_INDIRECTREPLY_WIDTH 32
#define SUME_STATS_1_INDIRECTCOMMAND_OFFSET 0x10C
#define SUME_STATS_1_INDIRECTCOMMAND_DEFAULT 0x0
#define SUME_STATS_1_INDIRECTCOMMAND_WIDTH 32
#define SUME_STATS_1_INDIRECTCONFIG_OFFSET 0x110
#define SUME_STATS_1_INDIRECTCONFIG_DEFAULT 0x0
#define SUME_STATS_1_INDIRECTCONFIG_WIDTH 32
#define SUME_STATS_1__MEM_PKTSIZEMEM_WIDTH 32
#define SUME_STATS_1__MEM_PKTSIZEMEM_DEPTH 2048
#define SUME_STATS_1__MEM_PKTSIZEMEM_ADDRESS 0x0
#define SUME_STATS_1__MEM_IPGMEM_WIDTH 32
#define SUME_STATS_1__MEM_IPGMEM_DEPTH 4096
#define SUME_STATS_1__MEM_IPGMEM_ADDRESS 0x10000000
#define SUME_STATS_1__MEM_BURSTMEM_WIDTH 32
#define SUME_STATS_1__MEM_BURSTMEM_DEPTH 8192
#define SUME_STATS_1__MEM_BURSTMEM_ADDRESS 0x20000000
#define SUME_STATS_1__MEM_BWMEM_WIDTH 32
#define SUME_STATS_1__MEM_BWMEM_DEPTH 8192
#define SUME_STATS_1__MEM_BWMEM_ADDRESS 0x30000000
#define SUME_STATS_1__MEM_BWTSMEM_WIDTH 32
#define SUME_STATS_1__MEM_BWTSMEM_DEPTH 8192
#define SUME_STATS_1__MEM_BWTSMEM_ADDRESS 0x40000000
#define SUME_STATS_1__MEM_PPSMEM_WIDTH 32
#define SUME_STATS_1__MEM_PPSMEM_DEPTH 8192
#define SUME_STATS_1__MEM_PPSMEM_ADDRESS 0x50000000
#define SUME_STATS_1__MEM_FLOWIDMEM_WIDTH 32
#define SUME_STATS_1__MEM_FLOWIDMEM_DEPTH 2048
#define SUME_STATS_1__MEM_FLOWIDMEM_ADDRESS 0x60000000
#define SUME_STATS_1__MEM_WINDOWSIZEMEM_WIDTH 32
#define SUME_STATS_1__MEM_WINDOWSIZEMEM_DEPTH 2048
#define SUME_STATS_1__MEM_WINDOWSIZEMEM_ADDRESS 0x70000000

//######################################################
//# Definitions for NF_10G_INTERFACE0
//######################################################
#define SUME_NF_10G_INTERFACE0_BASEADDR 0x44070000
#define SUME_NF_10G_INTERFACE0_HIGHADDR 0x44070FFF
#define SUME_NF_10G_INTERFACE0_SIZEADDR 0x1000

#define SUME_NF_10G_INTERFACE_SHARED_0_ID_OFFSET 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_ID_DEFAULT 0x00001F10
#define SUME_NF_10G_INTERFACE_SHARED_0_ID_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_VERSION_OFFSET 0x4
#define SUME_NF_10G_INTERFACE_SHARED_0_VERSION_DEFAULT 0x1
#define SUME_NF_10G_INTERFACE_SHARED_0_VERSION_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_RESET_OFFSET 0x8
#define SUME_NF_10G_INTERFACE_SHARED_0_RESET_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_RESET_WIDTH 16
#define SUME_NF_10G_INTERFACE_SHARED_0_FLIP_OFFSET 0xC
#define SUME_NF_10G_INTERFACE_SHARED_0_FLIP_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_FLIP_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_DEBUG_OFFSET 0x10
#define SUME_NF_10G_INTERFACE_SHARED_0_DEBUG_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_DEBUG_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_INTERFACEID_OFFSET 0x14
#define SUME_NF_10G_INTERFACE_SHARED_0_INTERFACEID_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_INTERFACEID_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PKTIN_OFFSET 0x18
#define SUME_NF_10G_INTERFACE_SHARED_0_PKTIN_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PKTIN_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PKTOUT_OFFSET 0x1C
#define SUME_NF_10G_INTERFACE_SHARED_0_PKTOUT_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PKTOUT_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_MACSTATUSVECTOR_OFFSET 0x20
#define SUME_NF_10G_INTERFACE_SHARED_0_MACSTATUSVECTOR_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_MACSTATUSVECTOR_WIDTH 2
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUS_OFFSET 0x24
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUS_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUS_WIDTH 8
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR0_OFFSET 0x28
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR0_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR0_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR1_OFFSET 0x2C
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR1_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR1_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR2_OFFSET 0x30
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR2_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR2_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR3_OFFSET 0x34
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR3_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR3_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR4_OFFSET 0x38
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR4_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR4_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR5_OFFSET 0x3C
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR5_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR5_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR6_OFFSET 0x40
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR6_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR6_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR7_OFFSET 0x44
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR7_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR7_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR8_OFFSET 0x48
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR8_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR8_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR9_OFFSET 0x4C
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR9_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR9_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR10_OFFSET 0x50
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR10_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR10_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR11_OFFSET 0x54
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR11_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR11_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR12_OFFSET 0x58
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR12_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR12_WIDTH 32
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR13_OFFSET 0x5C
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR13_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_SHARED_0_PCSPMASTATUSVECTOR13_WIDTH 32

//######################################################
//# Definitions for NF_10G_INTERFACE1
//######################################################
#define SUME_NF_10G_INTERFACE1_BASEADDR 0x44080000
#define SUME_NF_10G_INTERFACE1_HIGHADDR 0x44080FFF
#define SUME_NF_10G_INTERFACE1_SIZEADDR 0x1000

#define SUME_NF_10G_INTERFACE_1_ID_OFFSET 0x0
#define SUME_NF_10G_INTERFACE_1_ID_DEFAULT 0x00001F10
#define SUME_NF_10G_INTERFACE_1_ID_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_VERSION_OFFSET 0x4
#define SUME_NF_10G_INTERFACE_1_VERSION_DEFAULT 0x1
#define SUME_NF_10G_INTERFACE_1_VERSION_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_RESET_OFFSET 0x8
#define SUME_NF_10G_INTERFACE_1_RESET_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_RESET_WIDTH 16
#define SUME_NF_10G_INTERFACE_1_FLIP_OFFSET 0xC
#define SUME_NF_10G_INTERFACE_1_FLIP_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_FLIP_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_DEBUG_OFFSET 0x10
#define SUME_NF_10G_INTERFACE_1_DEBUG_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_DEBUG_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_INTERFACEID_OFFSET 0x14
#define SUME_NF_10G_INTERFACE_1_INTERFACEID_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_INTERFACEID_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PKTIN_OFFSET 0x18
#define SUME_NF_10G_INTERFACE_1_PKTIN_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PKTIN_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PKTOUT_OFFSET 0x1C
#define SUME_NF_10G_INTERFACE_1_PKTOUT_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PKTOUT_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_MACSTATUSVECTOR_OFFSET 0x20
#define SUME_NF_10G_INTERFACE_1_MACSTATUSVECTOR_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_MACSTATUSVECTOR_WIDTH 2
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUS_OFFSET 0x24
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUS_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUS_WIDTH 8
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR0_OFFSET 0x28
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR0_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR0_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR1_OFFSET 0x2C
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR1_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR1_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR2_OFFSET 0x30
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR2_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR2_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR3_OFFSET 0x34
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR3_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR3_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR4_OFFSET 0x38
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR4_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR4_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR5_OFFSET 0x3C
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR5_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR5_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR6_OFFSET 0x40
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR6_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR6_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR7_OFFSET 0x44
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR7_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR7_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR8_OFFSET 0x48
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR8_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR8_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR9_OFFSET 0x4C
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR9_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR9_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR10_OFFSET 0x50
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR10_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR10_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR11_OFFSET 0x54
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR11_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR11_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR12_OFFSET 0x58
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR12_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR12_WIDTH 32
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR13_OFFSET 0x5C
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR13_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_1_PCSPMASTATUSVECTOR13_WIDTH 32

//######################################################
//# Definitions for NF_10G_INTERFACE2
//######################################################
#define SUME_NF_10G_INTERFACE2_BASEADDR 0x44090000
#define SUME_NF_10G_INTERFACE2_HIGHADDR 0x44080FFF
#define SUME_NF_10G_INTERFACE2_SIZEADDR 0x1000

#define SUME_NF_10G_INTERFACE_2_ID_OFFSET 0x0
#define SUME_NF_10G_INTERFACE_2_ID_DEFAULT 0x00001F10
#define SUME_NF_10G_INTERFACE_2_ID_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_VERSION_OFFSET 0x4
#define SUME_NF_10G_INTERFACE_2_VERSION_DEFAULT 0x1
#define SUME_NF_10G_INTERFACE_2_VERSION_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_RESET_OFFSET 0x8
#define SUME_NF_10G_INTERFACE_2_RESET_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_RESET_WIDTH 16
#define SUME_NF_10G_INTERFACE_2_FLIP_OFFSET 0xC
#define SUME_NF_10G_INTERFACE_2_FLIP_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_FLIP_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_DEBUG_OFFSET 0x10
#define SUME_NF_10G_INTERFACE_2_DEBUG_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_DEBUG_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_INTERFACEID_OFFSET 0x14
#define SUME_NF_10G_INTERFACE_2_INTERFACEID_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_INTERFACEID_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PKTIN_OFFSET 0x18
#define SUME_NF_10G_INTERFACE_2_PKTIN_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PKTIN_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PKTOUT_OFFSET 0x1C
#define SUME_NF_10G_INTERFACE_2_PKTOUT_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PKTOUT_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_MACSTATUSVECTOR_OFFSET 0x20
#define SUME_NF_10G_INTERFACE_2_MACSTATUSVECTOR_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_MACSTATUSVECTOR_WIDTH 2
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUS_OFFSET 0x24
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUS_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUS_WIDTH 8
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR0_OFFSET 0x28
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR0_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR0_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR1_OFFSET 0x2C
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR1_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR1_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR2_OFFSET 0x30
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR2_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR2_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR3_OFFSET 0x34
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR3_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR3_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR4_OFFSET 0x38
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR4_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR4_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR5_OFFSET 0x3C
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR5_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR5_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR6_OFFSET 0x40
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR6_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR6_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR7_OFFSET 0x44
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR7_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR7_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR8_OFFSET 0x48
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR8_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR8_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR9_OFFSET 0x4C
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR9_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR9_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR10_OFFSET 0x50
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR10_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR10_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR11_OFFSET 0x54
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR11_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR11_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR12_OFFSET 0x58
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR12_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR12_WIDTH 32
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR13_OFFSET 0x5C
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR13_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_2_PCSPMASTATUSVECTOR13_WIDTH 32

//######################################################
//# Definitions for NF_10G_INTERFACE3
//######################################################
#define SUME_NF_10G_INTERFACE3_BASEADDR 0x440A0000
#define SUME_NF_10G_INTERFACE3_HIGHADDR 0x44080FFF
#define SUME_NF_10G_INTERFACE3_SIZEADDR 0x1000

#define SUME_NF_10G_INTERFACE_3_ID_OFFSET 0x0
#define SUME_NF_10G_INTERFACE_3_ID_DEFAULT 0x00001F10
#define SUME_NF_10G_INTERFACE_3_ID_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_VERSION_OFFSET 0x4
#define SUME_NF_10G_INTERFACE_3_VERSION_DEFAULT 0x1
#define SUME_NF_10G_INTERFACE_3_VERSION_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_RESET_OFFSET 0x8
#define SUME_NF_10G_INTERFACE_3_RESET_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_RESET_WIDTH 16
#define SUME_NF_10G_INTERFACE_3_FLIP_OFFSET 0xC
#define SUME_NF_10G_INTERFACE_3_FLIP_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_FLIP_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_DEBUG_OFFSET 0x10
#define SUME_NF_10G_INTERFACE_3_DEBUG_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_DEBUG_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_INTERFACEID_OFFSET 0x14
#define SUME_NF_10G_INTERFACE_3_INTERFACEID_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_INTERFACEID_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PKTIN_OFFSET 0x18
#define SUME_NF_10G_INTERFACE_3_PKTIN_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PKTIN_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PKTOUT_OFFSET 0x1C
#define SUME_NF_10G_INTERFACE_3_PKTOUT_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PKTOUT_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_MACSTATUSVECTOR_OFFSET 0x20
#define SUME_NF_10G_INTERFACE_3_MACSTATUSVECTOR_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_MACSTATUSVECTOR_WIDTH 2
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUS_OFFSET 0x24
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUS_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUS_WIDTH 8
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR0_OFFSET 0x28
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR0_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR0_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR1_OFFSET 0x2C
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR1_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR1_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR2_OFFSET 0x30
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR2_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR2_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR3_OFFSET 0x34
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR3_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR3_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR4_OFFSET 0x38
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR4_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR4_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR5_OFFSET 0x3C
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR5_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR5_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR6_OFFSET 0x40
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR6_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR6_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR7_OFFSET 0x44
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR7_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR7_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR8_OFFSET 0x48
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR8_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR8_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR9_OFFSET 0x4C
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR9_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR9_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR10_OFFSET 0x50
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR10_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR10_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR11_OFFSET 0x54
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR11_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR11_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR12_OFFSET 0x58
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR12_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR12_WIDTH 32
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR13_OFFSET 0x5C
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR13_DEFAULT 0x0
#define SUME_NF_10G_INTERFACE_3_PCSPMASTATUSVECTOR13_WIDTH 32

//######################################################
//# Definitions for NF_RIFFA_DMA
//######################################################
#define SUME_NF_RIFFA_DMA_BASEADDR 0x440B0000
#define SUME_NF_RIFFA_DMA_HIGHADDR 0x44080FFF
#define SUME_NF_RIFFA_DMA_SIZEADDR 0x1000

#define SUME_NF_RIFFA_DMA_0_ID_OFFSET 0x0
#define SUME_NF_RIFFA_DMA_0_ID_DEFAULT 0x00001FFA
#define SUME_NF_RIFFA_DMA_0_ID_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_VERSION_OFFSET 0x4
#define SUME_NF_RIFFA_DMA_0_VERSION_DEFAULT 0x1
#define SUME_NF_RIFFA_DMA_0_VERSION_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_RESET_OFFSET 0x8
#define SUME_NF_RIFFA_DMA_0_RESET_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_RESET_WIDTH 16
#define SUME_NF_RIFFA_DMA_0_FLIP_OFFSET 0xC
#define SUME_NF_RIFFA_DMA_0_FLIP_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_FLIP_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_DEBUG_OFFSET 0x10
#define SUME_NF_RIFFA_DMA_0_DEBUG_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_DEBUG_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_RQPKT_OFFSET 0x14
#define SUME_NF_RIFFA_DMA_0_RQPKT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_RQPKT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_RCPKT_OFFSET 0x18
#define SUME_NF_RIFFA_DMA_0_RCPKT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_RCPKT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_CQPKT_OFFSET 0x1C
#define SUME_NF_RIFFA_DMA_0_CQPKT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_CQPKT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_CCPKT_OFFSET 0x20
#define SUME_NF_RIFFA_DMA_0_CCPKT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_CCPKT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_XGETXPKT_OFFSET 0x24
#define SUME_NF_RIFFA_DMA_0_XGETXPKT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_XGETXPKT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_XGERXPKT_OFFSET 0x28
#define SUME_NF_RIFFA_DMA_0_XGERXPKT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_XGERXPKT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIERQ_OFFSET 0x2C
#define SUME_NF_RIFFA_DMA_0_PCIERQ_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIERQ_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEPHY_OFFSET 0x30
#define SUME_NF_RIFFA_DMA_0_PCIEPHY_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEPHY_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIECONFIG_OFFSET 0x34
#define SUME_NF_RIFFA_DMA_0_PCIECONFIG_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIECONFIG_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIECONFIG2_OFFSET 0x38
#define SUME_NF_RIFFA_DMA_0_PCIECONFIG2_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIECONFIG2_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEERROR_OFFSET 0x3C
#define SUME_NF_RIFFA_DMA_0_PCIEERROR_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEERROR_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEMISC_OFFSET 0x40
#define SUME_NF_RIFFA_DMA_0_PCIEMISC_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEMISC_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIETPH_OFFSET 0x44
#define SUME_NF_RIFFA_DMA_0_PCIETPH_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIETPH_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEFC1_OFFSET 0x48
#define SUME_NF_RIFFA_DMA_0_PCIEFC1_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEFC1_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEFC2_OFFSET 0x4C
#define SUME_NF_RIFFA_DMA_0_PCIEFC2_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEFC2_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEFC3_OFFSET 0x50
#define SUME_NF_RIFFA_DMA_0_PCIEFC3_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEFC3_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEINTERRUPT_OFFSET 0x54
#define SUME_NF_RIFFA_DMA_0_PCIEINTERRUPT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEINTERRUPT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEMSIDATA_OFFSET 0x58
#define SUME_NF_RIFFA_DMA_0_PCIEMSIDATA_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEMSIDATA_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEMSIINT_OFFSET 0x5C
#define SUME_NF_RIFFA_DMA_0_PCIEMSIINT_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEMSIINT_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEMSIPENDINGSTATUS_OFFSET 0x60
#define SUME_NF_RIFFA_DMA_0_PCIEMSIPENDINGSTATUS_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEMSIPENDINGSTATUS_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEMSIPENDINGSTATUS2_OFFSET 0x64
#define SUME_NF_RIFFA_DMA_0_PCIEMSIPENDINGSTATUS2_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEMSIPENDINGSTATUS2_WIDTH 32
#define SUME_NF_RIFFA_DMA_0_PCIEINTERRUPT2_OFFSET 0x68
#define SUME_NF_RIFFA_DMA_0_PCIEINTERRUPT2_DEFAULT 0x0
#define SUME_NF_RIFFA_DMA_0_PCIEINTERRUPT2_WIDTH 32

